HanKyungPark/DevLog

src/main/java/org/bitcamp/devlog/DevlogApplication.java, src/main/java/org/bitcamp/devlog/dto/Post.java, src/main/java/org/bitcamp/devlog/dto/PostTagJoin.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/resources/dockerfile, src/main/resources/mapper/Post.xml, src/main/resources/templates/contents/feedPage.html, src/main/resources/templates/contents/mainPage.html, src/main/resources/templates/contents/myBlogPage.html, src/main/resources/templates/contents/myPage.html, src/main/resources/templates/contents/postingDetail.html, src/main/resources/templates/contents/postingForm.html, src/main/resources/templates/contents/updateForm.html, src/main/resources/templates/layout/layout_ele/footer.html, src/main/resources/templates/layout/layout_ele/header.html, src/main/resources/templates/layout/layout_main/layout1_hmenu.html, src/main/resources/templates/layout/layout_main/layout2_vmenu.html
PostMapper 작성,
PostTagJoin Class 생성,
Post Class 추가
=> PostMapper 작성

src/main/java/org/bitcamp/devlog/controller/account/AccountRestController.java, src/main/java/org/bitcamp/devlog/controller/account/AccountServController.java, src/main/java/org/bitcamp/devlog/mapper/CommentMapper.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/mapper/PostTagMapper.java, src/main/java/org/bitcamp/devlog/mapper/TagMapper.java, src/main/resources/application.yaml, src/main/resources/mapper/Comment.xml, src/main/resources/mapper/Post.xml, src/main/resources/mapper/PostTag.xml, src/main/resources/mapper/Tag.xml
=> 댓글,태그 mapper작성

build.gradle, src/main/java/org/bitcamp/devlog/config/SecurityConfig.java, src/main/java/org/bitcamp/devlog/controller/HomeServCotroller.java, src/main/java/org/bitcamp/devlog/dto/Account.java, src/main/java/org/bitcamp/devlog/dto/AccountResponse.java, src/main/java/org/bitcamp/devlog/dto/Oauth2User.java, src/main/java/org/bitcamp/devlog/mapper/AccountMapper.java, src/main/java/org/bitcamp/devlog/mapper/AccountRoleMapper.java, src/main/java/org/bitcamp/devlog/service/Oauth2UserService.java, src/main/resources/application.yaml, src/main/resources/mapper/Account.xml, src/main/resources/mapper/Account_Role.xml, src/main/resources/templates/contents/feedPage.html, src/main/resources/templates/contents/mainPage.html, src/main/resources/templates/contents/myBlogPage.html, src/main/resources/templates/contents/myPage.html, src/main/resources/templates/contents/postingDetail.html, src/main/resources/templates/contents/postingForm.html, src/main/resources/templates/contents/updateForm.html, src/main/resources/templates/index.html, src/main/resources/templates/layout/layout_ele/footer.html, src/main/resources/templates/layout/layout_ele/header.html
=> 소셜로그인 (카카오)연동

build.gradle, src/main/java/org/bitcamp/devlog/controller/HomeServCotroller.java, src/main/java/org/bitcamp/devlog/mapper/VisitMapper.java, src/main/resources/mapper/Visit.xml, src/main/resources/static/css/footer.css, src/main/resources/static/css/header.css, src/main/resources/static/css/hmenu.css, src/main/resources/static/css/layout1_hmenu.css, src/main/resources/static/css/layout2_vmenu.css, src/main/resources/static/css/mainPage.css, src/main/resources/static/css/vmenu.css, src/main/resources/templates/contents/feedPage.html, src/main/resources/templates/contents/mainPage.html, src/main/resources/templates/contents/myBlogPage.html, src/main/resources/templates/contents/myPage.html, src/main/resources/templates/contents/postingDetail.html, src/main/resources/templates/contents/postingForm.html, src/main/resources/templates/contents/updateForm.html, src/main/resources/templates/layout/layout_ele/footer.html, src/main/resources/templates/layout/layout_ele/header.html, src/main/resources/templates/layout/layout_ele/hmenu.html, src/main/resources/templates/layout/layout_ele/vmenu.html, src/main/resources/templates/layout/layout_main/layout1_hmenu.html, src/main/resources/templates/layout/layout_main/layout2_vmenu.html
=> layout + visit mapper 작성

src/main/java/org/bitcamp/devlog/service/Oauth2UserService.java
=> saveAcoount 수정

src/main/resources/application.yaml
=> redirect url 수정

src/main/java/org/bitcamp/devlog/config/SecurityConfig.java, src/main/java/org/bitcamp/devlog/mapper/CommentMapper.java, src/main/java/org/bitcamp/devlog/service/CommentService.java, src/main/java/org/bitcamp/devlog/service/PostTagService.java, src/main/java/org/bitcamp/devlog/service/TagService.java, src/main/resources/mapper/Tag.xml
=> comment, tag, postag service 작성

src/main/java/org/bitcamp/devlog/mapper/CategoryMapper.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/service/CategoryService.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/resources/mapper/Category.xml
=> Categorty 수정 및 PostService 생성

src/main/java/org/bitcamp/devlog/controller/account/AccountRestController.java, src/main/java/org/bitcamp/devlog/dto/Oauth2User.java, src/main/java/org/bitcamp/devlog/mapper/AccountMapper.java, src/main/java/org/bitcamp/devlog/service/AccountService.java, src/main/java/org/bitcamp/devlog/service/Oauth2UserService.java, src/main/resources/mapper/Account.xml, src/main/resources/static/js/loginForm.js
=> 블로그 생성 db 값 저장

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/resources/mapper/Account_Role.xml, src/main/resources/mapper/Follower.xml, src/main/resources/mapper/Heart.xml, src/main/resources/mapper/Notification.xml, src/main/resources/mapper/Role.xml, src/main/resources/mapper/Visit.xml
Mapper가 빠진 경로에 Mapper를 추가하였습니다.
=> mapper.xml 경로 이름 수정

src/main/java/org/bitcamp/devlog/controller/category/CategoryRestController.java, src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/dto/Account.java, src/main/java/org/bitcamp/devlog/dto/Post.java, src/main/java/org/bitcamp/devlog/mapper/CategoryMapper.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/mapper/PostTagMapper.java, src/main/java/org/bitcamp/devlog/service/CategoryService.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/java/org/bitcamp/devlog/service/PostTagService.java, src/main/resources/mapper/Category.xml, src/main/resources/mapper/Post.xml, src/main/resources/mapper/PostTag.xml, src/main/resources/mapper/Tag.xml, src/main/resources/static/js/postingForm.js, src/main/resources/templates/contents/postingForm.html
=> 포스트 작성 페이지

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/controller/post/PostServController.java, src/main/resources/static/css/myBlogPage.css, src/main/resources/static/js/myBlogPage.js, src/main/resources/templates/contents/myBlogPage.html
=> myblog css변경

src/main/java/org/bitcamp/devlog/controller/category/CategoryRestController.java, src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java
=> 카테고리 오류 수정

src/main/java/org/bitcamp/devlog/controller/heart/HeartRestController.java, src/main/java/org/bitcamp/devlog/mapper/HeartMapper.java, src/main/java/org/bitcamp/devlog/service/HeartService.java, src/main/resources/mapper/Heart.xml
Heart.xml
HeartService.java
HeartRestControllor.java
=> Heart 로직 작성

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/resources/static/js/myPage.js
게시글 카테고리 저장이 되지 않는 오류를 해결하였습니다.
=> 게시글 작성 오류 해결

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/service/HeartService.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/resources/mapper/Post.xml, src/main/resources/mapper/Visit.xml, src/main/resources/static/js/myBlogPage.js, src/main/resources/templates/contents/myBlogPage.html
=> my blog page views 구현

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/resources/mapper/Post.xml, src/main/resources/static/js/feedPage.js
공개여부에 따른 게시글 조회 가능여부에 대한 작업을 하였습니다.
=> 게시글 조회가능 여부

src/main/java/org/bitcamp/devlog/controller/category/CategoryRestController.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/service/CategoryService.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/resources/mapper/Category.xml, src/main/resources/mapper/Post.xml, src/main/resources/static/css/postingDetail.css, src/main/resources/static/js/myPage.js, src/main/resources/static/js/postingDetail.js, src/main/resources/templates/contents/homePage.html, src/main/resources/templates/contents/myPage.html, src/main/resources/templates/contents/postingDetail.html, src/main/resources/templates/layout/layout_ele/footer.html
마이페이지 카테고리 오류 수정하였습니다
오류내용: 카테고리 리스트가 클라이언트에서 보이지 않는다
해결방법: 서버에서 카테고리 리스트를 보내주는 로직 수정
=> mypage error 수정

src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/mapper/PostMapper.java, src/main/java/org/bitcamp/devlog/service/PostService.java, src/main/resources/mapper/Post.xml, src/main/resources/static/js/myBlogPage.js, src/main/resources/templates/contents/myBlogPage.html
=> my blog page category 수정

src/main/java/org/bitcamp/devlog/controller/heart/HeartRestController.java, src/main/java/org/bitcamp/devlog/controller/post/PostRestController.java, src/main/java/org/bitcamp/devlog/service/HeartService.java, src/main/resources/mapper/Heart.xml, src/main/resources/mapper/Post.xml, src/main/resources/static/js/feedPage.js, src/main/resources/static/js/myPage.js, src/main/resources/templates/contents/feedPage.html, src/main/resources/templates/contents/myPage.html
=> 마이페이지 포스트 에러

src/main/java/org/bitcamp/devlog/mapper/HeartMapper.java, src/main/java/org/bitcamp/devlog/service/HeartService.java, src/main/resources/mapper/Heart.xml, src/main/resources/static/js/feedPage.js
=> feedpage 좋아요

src/main/resources/mapper/Post.xml, src/main/resources/static/js/myBlogPage.js, src/main/resources/templates/contents/myBlogPage.html
my blog page 새글 쓰기 버튼 수정 및 카테고리 null값 출력
=> my blog page 새글 쓰기 버튼 수정 및 카테고리 null값 출력

src/main/java/org/bitcamp/devlog/controller/account/AccountRestController.java
=> blog 저장 로직 수정
